### ISSUE TITLE
Regarding testing the model

### ISSUE THREAD

**Issue by yash-iiith** [bethgelab/siamese-mask-rcnn#12] opened 2019-06-26 10:24 UTC
I have trained the model using train.ipynb on a subset of coco dataset(i.e only on first 10 categories). How do I test the model on an image which doesn't belong to the coco dataset? I want to give explicitly a reference image and a query image. Please help me with this.

**Comment by michaelisc** [comment] 2019-06-26 11:02
Do you have annotations for your image? 

If you only want to visualize the results you can use the visualization example from the `evaluate.ipynb`. Just replace the image and target loading and load your own image and target.

If you have labels for your images you will have to bring them into the Coco format or write your own evaluation function.

**Comment by michaelisc** [comment] 2019-06-26 11:05
Oh and I would be interested to hear, how a model performs, that was trained on such a small subset. Be however aware, that the scaling of the images and some other hyperparameters are different in `train.ipynb` than in our experiments. `train.ipynb` is thought as a quick starting point without the time and resource requirements of the full model. The full model training function can be found in `experiments/train_parallel_coco_full.ipynb`.

**Comment by yash-iiith** [comment] 2019-07-01 10:21
@michaelisc What is the difference between `experiments/train_parallel_coco_full.ipynb` and `experiments/train_parallel_mrcnn_coco_full.ipynb`?

**Comment by yash-iiith** [comment] 2019-07-01 11:40
I don't have the annotations for the images I want to test. I just have some images and the the cropped object images. And I want to be able to give a (query image, reference image) pair and get the bounding box/segmentation mask for the query image.

**Comment by michaelisc** [comment] 2019-07-01 12:22
Then use the visualization tool, which will compute the bounding box and segmentation mask and show them to you. If you want to run this on many images just comment out the visualization step and save the predictions.

**Comment by michaelisc** [comment] 2019-07-01 12:24
Considering the difference between `experiments/train_parallel_coco_full.ipynb` and `experiments/train_parallel_mrcnn_coco_full.ipynb`:

`experiments/train_parallel_coco_full.ipynb` contains code to train **siamese mask r-cnn**
`experiments/train_parallel_mrcnn_coco_full.ipynb`contains code to  to train **standard mask r-cnn**

**Comment by yash-iiith** [comment] 2019-07-02 11:02
I am trying to test the model that I trained using `experiments/train_parallel_coco_full.ipynb`. I am using `siamese-mask-rcnn/evaluate.ipynb` to test. I have changed the parameters in the Eval_config according to the parameters given in Train_config in `experiments/train_parallel_coco_full.ipynb`
It gives me a ValueError when I run it :
`ValueError: Error when checking : expected input_target to have 5 dimensions, but got array with shape (1, 192, 192, 3)`
I have attached the error picture. Please help me solve this.
<img width="388" alt="Capture" src="https://user-images.githubusercontent.com/15844831/60507497-ea11f500-9ce5-11e9-9315-9acccc4e92a8.PNG">

**Comment by michaelisc** [comment] 2019-07-02 11:11
This happens, because the model config is different. To evaluate your model use `experiments/evaluate-experiments.ipynb`. `evaluate.ipynb` is by default configured to evaluate the small models from `train.ipynb`. 

I see, that this is confusing not only for you. I will think about a good solution. Let me know, if you have any suggestions!

**Comment by michaelisc** [comment] 2019-07-02 11:11
Alternatively you can of course change the `EvalConfig` class in `evaluate.ipynb` to match the `ParallelTrainConfig` in `experiments/evaluate-experiments.ipynb`.

**Comment by yash-iiith** [comment] 2019-07-03 07:47
The problem was with the dimensions of the target being passed to model.detect . I put one more pair of brackets in the target while passing it to model.detect and it worked.
`results = model.detect( [ [target] ] , [image] , verbose=1 )`

**Comment by michaelisc** [comment] 2019-07-03 15:37
Thanks for catching this! When we added few-shot training and evaluation, we decided to feed the targets simply as a list. I forgot to transfer this to the visualization example. 
Should be fixed with commit [54feacb](https://github.com/bethgelab/siamese-mask-rcnn/commit/54feacb43148a42d680338c70457569842a48cde)

**Comment by yash-iiith** [comment] 2019-07-05 09:30
Also, change the parameter name being passed to model.load_latest_checkpoint() from train_schedule to training schedule in `siamese-mask-rcnn/train.ipynb`.
`model.load_latest_checkpoint(train_schedule=train_schedule)` to `model.load_latest_checkpoint(training_schedule=train_schedule)`

**Comment by yash-iiith** [comment] 2019-07-05 09:46
In `siamese-mask-rcnn/lib/Mask_RCNN/samples/coco/coco.py`, lines 136 - 140, it has been explicitly mentioned to take the last 3000 images for validation and the remaining images for training. This can be troubling when we train it on a different, smaller dataset(or when we are fine tuning it on very small datasets). I feel images(or data) should be split into training and validation on the basis of percentage(90,10 maybe). I had been getting errors when I was fine tuning it. Spent a lot of time on this. Please mention about it somewhere in the Readme.

**Comment by michaelisc** [comment] 2019-07-05 11:55
Thanks for catching all those errors!

The first one should be fixed with commit [d84d50d](https://github.com/bethgelab/siamese-mask-rcnn/commit/d84d50d7cbb24291956d1fa2c749a8eb3874c177)

The second one is more difficult, so I followed your suggestion and added this information to the readme. I also added the large models to the `train.ipynb` and evaluation.`ipynb` as this has confused many people in the past. See commit [d66a9d0](https://github.com/bethgelab/siamese-mask-rcnn/commit/d66a9d03502b5c3d1b96f57ce4acc56ef3908614)

**Comment by yash-iiith** [comment] 2019-07-08 06:37
Are there any more places in the code where a similar hardcoding has been done specific to coco dataset? I am trying to run the model on a smaller dataset(in coco format), but I am getting `list index out of range` error with `category_image_index`. Please help me with this. Stuck on it for a long time now.

**Comment by yash-iiith** [comment] 2019-07-08 13:37
What does `category_image_index[0]` denote? Is the 0 index for background? Because the category IDs start from 1 to 80. `category_image_index[i]` stores the list of image_ids which have an annotation of category_id = i. Please confirm this.

**Comment by michaelisc** [comment] 2019-07-09 15:44
Sorry for the late reply: You are right, the `category_image_index[i]` stores a list of image_ids, which contain at least one instance from that category. `category_image_index[0]` remains empty. Even though all images contain background this is not seen as a category of it's own.

**Comment by michaelisc** [comment] 2019-07-09 15:50
One important step that might be the cause of your problems is the mapping from coco category ids (which are in [1:91] containing categories which have no instance in the dataset) to [1:80]. 
This is done using the `dataset.map_source_class_id` function from the `CocoDataset` class defined in `lib/Mask_RCNN/samples/coco/coco.py`. If your dataset has different categories than coco this mapping might create the indexing problem.

**Comment by michaelisc** [comment] 2019-07-16 20:46
I hope I was able to answer your questions and will close this issue now.

**Closed by michaelisc** 2019-07-16 20:46 UTC
Labels: question
