### ISSUE TITLE
Problem occurred in evaluate.ipynb

### ISSUE THREAD

**Issue by DL-Alva** [bethgelab/siamese-mask-rcnn#8] opened 2019-04-20 07:43 UTC
When I run this part of code:
# Load and evaluate model
# Create model object in inference mode.
model = siamese_model.SiameseMaskRCNN(mode="inference", model_dir=MODEL_DIR, config=config)
model.load_checkpoint(checkpoint, training_schedule=train_schedule)
# Evaluate only active classes
active_class_idx = np.array(coco_val.ACTIVE_CLASSES) - 1

# Evaluate on the validation set
print('starting evaluation ...')
siamese_utils.evaluate_dataset(model, coco_val, coco_object, eval_type="bbox", 
                 dataset_type='coco', limit=0, image_ids=None, 
                 class_index=active_class_idx, verbose=1)

It reminds me ValueError: `Subtract` layer should be called on inputs of the same shape.
However, it can run successfully when I convert the evaluate.jpynb into the file of evaluate.py.

**Comment by happycoding1996** [comment] 2019-08-10 20:52
@DL-Alva  Could you tell me how you convert the ipynb to py? I directly copy code from ipynb to py and the same error is reported. Thank you!

**Comment by michaelisc** [comment] 2020-01-03 17:30
I was not able to reproduce this issue and will thus close it now! Please let me know if anyone else runs into the same problem!

**Closed by michaelisc** 2020-01-03 17:30 UTC
